spring:
  application:
    name: coral-ms

  datasource:
    url: jdbc:h2:mem:coral-db
    driverClassName: org.h2.Driver
    username: user
    password: password

  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
    #show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

core-banking:
  api:
    base-url: http://localhost:8080
    transactions-path: /transactions